### ISSUE TITLE
npm test is not running

### ISSUE THREAD

**Issue by torabian** [smart-dashboard/angular-dashboard#4]
We have problem to run tests before merging into master branch. We currently only build the project and if it works, we decide to able to be merge.

You must find out how to run `npm test` on travis CI to check the results.

**Comment by kidchenko** [comment]
There are several reasons that are broken the tests:

- The components that use `Store` are broken because in the tests we need to inject the `StoreProvider`
- Components that use others components
- Components that use Highcharts jquery plugin

At the last there are some tests there are not working because some specific code in respectives componentes.

**Comment by torabian** [comment]
I've merged your PR, which solves 50% of test cases, thank you for your contribution. It gave me a good clue how to test the project.
Now I am making another Pr, to fix more components.

**Comment by torabian** [comment]
All tests are fixed.
